# Generated by Django 4.2.2 on 2023-07-21 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_referralcode'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReferralOffers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('referrer_amount', models.IntegerField()),
                ('referral_discount', models.IntegerField()),
                ('referral_description', models.CharField(max_length=100)),
            ],
        ),
    ]
