# Generated by Django 4.2.2 on 2023-07-25 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_personaldetails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personaldetails',
            name='contact',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='personaldetails',
            name='country',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='personaldetails',
            name='state',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
