# Generated by Django 4.2.2 on 2023-07-25 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0007_alter_personaldetails_contact_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Slider',
        ),
    ]
