# Generated by Django 4.2.2 on 2023-07-25 16:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('productside', '0005_productvariant_discount'),
        ('authentication', '0008_delete_slider'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Image', models.ImageField(upload_to='media/slider_images')),
                ('Discount_deals', models.CharField(choices=[('HOT DEALS', 'HOT DEALS'), ('NEW ARRIVALS', 'NEW ARRIVALS'), ('SPECIAL OFFERS', 'SPECIAL OFFERS')], max_length=100, null=True)),
                ('Product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='productside.productvariant')),
            ],
        ),
    ]
