# Generated by Django 4.2.2 on 2023-07-25 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0009_slider'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slider',
            name='Image',
            field=models.ImageField(upload_to='slider_images'),
        ),
    ]
