# Generated by Django 4.2.2 on 2023-07-02 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userside', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Address',
        ),
    ]
