# Generated by Django 4.2.1 on 2023-07-03 06:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userside', '0004_customer_order_product_orderlist'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Customer',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
