# Generated by Django 4.2.1 on 2023-07-03 07:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userside', '0005_delete_customer_delete_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderlist',
            name='order_id',
        ),
        migrations.RemoveField(
            model_name='orderlist',
            name='product',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='Orderlist',
        ),
    ]
