# Generated by Django 4.2.2 on 2023-07-05 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userside', '0009_alter_order_payment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('ORDERED', 'ordered'), ('SHIPPED', 'Shipped'), ('CANCELLED', 'Cancelled'), ('DELIVERED', 'Delivered')], default='ordered', max_length=20),
        ),
    ]
