# Generated by Django 4.2.2 on 2023-07-13 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userside', '0011_order_payment_id_alter_order_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='signature_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
