# Generated by Django 4.2.2 on 2023-07-13 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userside', '0012_order_signature_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='signature_id',
        ),
    ]
