# Generated by Django 4.2.2 on 2023-07-20 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userside', '0014_alter_order_payment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('PREPAID', 'Prepaid'), ('COD', 'Cash on Delivery'), ('WALLET', 'Wallet')], max_length=20),
        ),
    ]
