# Generated by Django 4.2.2 on 2023-07-01 06:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('productside', '0002_productvariant_slug'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cartside', '0002_rename_user_id_usercart_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercart',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cart_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cartside.usercart')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productside.productvariant')),
            ],
        ),
    ]
