# Generated by Django 4.2.2 on 2023-07-12 05:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('productside', '0003_coupon'),
        ('cartside', '0003_alter_usercart_user_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercart',
            name='coupon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='productside.coupon'),
        ),
    ]
