# Generated by Django 4.2.2 on 2023-07-13 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cartside', '0005_wallet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='money',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
