# Generated by Django 4.2.1 on 2023-06-30 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productside', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariant',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
