# Generated by Django 4.2.2 on 2023-07-15 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productside', '0004_productvariant_discount_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariant',
            name='discount',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
